ani_count = 0; ani_wait = 15;
ani_frame = 0;
dir = "down";
image_speed = 0; image_index = 0;
next_x = x; next_y = y;
state = "idle";
idle_animate = true;
movespeed = 2;
walk_movespeed = 2;
sprint_movespeed = 4;
sprinting = false;
char = -1;
update = false;
visible = false;
scoot = false;
scoot_dir = "down";
scoot_amount = 0;
scoot_count = 0;
step_pause = false;
use_newcol = false;
l_seablock = layer_tilemap_get_id("l_seablock");
has_boats = scr_hasitem(item_Boats);
depth += -1;
stress = false;