#macro view_xview __view_get( e__VW.XView, 0 )
#macro view_yview __view_get( e__VW.YView, 0 )

#macro TYPE_NONE 0
#macro TYPE_EQUIP 1
#macro TYPE_CONSUME 2
#macro TYPE_TOOL 3

#macro YELLOW #FF9A38
#macro RED #E70059

#macro LEVEL_CAP 254

#macro flag_MetDon 15 
#macro flag_MetBoats 16 
#macro flag_BeatHalls 17 
#macro flag_GotSong 18
#macro flag_ActiveTurtle 19
#macro flag_GotCrystal 20
#macro flag_GotMakeup 21
#macro flag_GotLevel 22
#macro flag_GotRoyalties 23
#macro flag_GotJewels 24
#macro flag_GaveJar 25
#macro flag_UsedPass 26
#macro flag_TriedSwim 27
#macro flag_ChickenOK 28
#macro flag_BottleActive 29
#macro flag_Endgame 30
#macro flag_WonQuiz 31

#macro paint_Violet 6
#macro paint_Indigo 5
#macro paint_Blue 4
#macro paint_Green 3
#macro paint_Yellow 2
#macro paint_Orange 1
#macro paint_Red 0

#macro DIR_DOWN 0
#macro DIR_RIGHT 1
#macro DIR_UP 2
#macro DIR_LEFT 3

#macro DOWN 0
#macro RIGHT 1
#macro UP 2
#macro LEFT 3

#macro ENM_NAME 0
#macro ENM_SPRITE 1
#macro ENM_HP 2
#macro ENM_ATK 3
#macro ENM_DEF 4
#macro ENM_PP 5
#macro ENM_MONEY 6
#macro ENM_STRESS 7
#macro ENM_ECCHI 8
#macro ENM_HEX 9

#macro SECRET_NONE 0
#macro SECRET_PAINT 1
#macro SECRET_FIELD 2
#macro SECRET_ITEM 3
#macro SECRET_SUIT 4
#macro SECRET_EQUIP 5
#macro SECRET_MONEY 6

#macro ANI_WAIT 0
#macro ANI_FLAP 1
#macro ANI_SWOOSH 2
#macro ANI_WAIT_R 3
#macro ANI_WAIT_L 4
#macro ANI_WALK_R 5
#macro ANI_WALK_L 6
#macro ANI_SPIN 7

#macro price_Concert 0
#macro price_WinMall 1
#macro price_Paint 2
#macro price_StarsDress 3

#macro suit_Bird 0
#macro suit_Cursed 1
#macro suit_Master 2
#macro suit_Fire 3
#macro suit_Ice 4
#macro suit_Steel 5
#macro suit_Banana 6
#macro suit_Light 7

#macro item_Pass 1
#macro item_WahaiiTicket 2
#macro item_CrystalBall 3
#macro item_BotsonTicket 4
#macro item_Jewels 5
#macro item_Sunorb 6
#macro item_Letter 7
#macro item_Micril 8
#macro item_Photo 9
#macro item_Grace 10
#macro item_AecorJar 11
#macro item_FreattleTicket 12
#macro item_Coupon 13
#macro item_MagicPaint 14
#macro item_Boats 15

#macro item_WaterBottle 16
#macro item_Burger 17
#macro item_WarpRing 18
#macro item_HealthyDrink 19
#macro item_HotDog 20
#macro item_Nicesword 21
#macro item_ButterSword 22
#macro item_SCape 23
#macro item_PeaceRing 24
#macro item_RosettaStone 25
#macro item_WhitePaint 26
#macro item_DoubleBurger 27
#macro item_Candy 28
#macro item_Banana 29
#macro item_CursedDress 30
#macro item_MasterCape 31

#macro item_SecretLens 32
#macro item_EasyRing 33
#macro item_CheeseSmoothie 34
#macro item_YummyBanana 35

#macro mic_None 0
#macro mic_Toy 1
#macro mic_Cheap 2
#macro mic_Metal 3
#macro mic_Comedy 4
#macro mic_Rocker 5
#macro mic_Singer 6
#macro mic_Stars 7

#macro dress_Casual 8
#macro dress_Used 9
#macro dress_Cheap 10
#macro dress_Silk 11
#macro dress_Peacock 12
#macro dress_Sparkly 13
#macro dress_Singer 14
#macro dress_Stars 15

#macro shoes_Barefoot 16
#macro shoes_Casual 17
#macro shoes_Sandles 18
#macro shoes_Heels 19
#macro shoes_Stilettos 20
#macro shoes_Emerald 21
#macro shoes_Singer 22
#macro shoes_Stars 23

#macro makeup_None 24
#macro makeup_Rouge 25
#macro makeup_Model 26
#macro makeup_Movie 27
#macro makeup_Actress 28
#macro makeup_Azure 29
#macro makeup_Singer 30
#macro makeup_Stars 31

#macro mng_BLJ 0
#macro mng_Ease 1
#macro mng_Nyce 2
#macro mng_Easamore 3
#macro mng_Acwaranos 4
#macro mng_Relaxanos 5
#macro mng_Nycamore 6
#macro mng_Easaramost 7

#macro hall_Melville 0
#macro hall_Kings 1
#macro hall_Niami 2
#macro hall_Fenix 3
#macro hall_Tallas 4
#macro hall_Metroit 5
#macro hall_NewYorik 6

#macro mall_Melville 0
#macro mall_Botson 1
#macro mall_Fenix 2
#macro mall_Tallas 3
#macro mall_Kings 4
#macro mall_Metroit 5
#macro mall_NoName 6

#macro town_Melville 0
#macro town_Arbony 1
#macro town_Freattle 2
#macro town_Kings 3

#macro town_Yutica 4
#macro town_Moonbark 5
#macro town_Boizy 6
#macro town_Lonohuhu 7

#macro city_NY 0
#macro city_Denber 1
#macro city_Botson 2
#macro city_Niami 3
#macro city_Fenix 4
#macro city_Tallas 5
#macro city_Metroit 6
#macro city_Poltland 7

#macro LEVEL_PP 0
#macro LEVEL_HP 1
#macro LEVEL_MP 2
#macro LEVEL_KND 3
#macro LEVEL_CNF 4
#macro LEVEL_CHM 5

#macro SHOP_HOTEL 0
#macro SHOP_EQUIP 1
#macro SHOP_ITEM 2
#macro SHOP_FOOD 3
#macro SHOP_AIRPORT 4
#macro SHOP_DON 5

#macro MIC 0
#macro DRESS 1
#macro SHOES 2
#macro MAKEUP 3

#macro BCK_HOTEL 0
#macro BCK_CITY 1
#macro BCK_OW 2
#macro BCK_OCEAN 3
#macro BCK_TUNNEL 4
#macro BCK_OFFICE 5
#macro BCK_ENGLISH 6
#macro BCK_OFFICE2 7
#macro BCK_MEOWCO 8
#macro BCK_OFFICE3 9
#macro BCK_RECORDS 10
#macro BCK_DUD 11
#macro BCK_FOOD 12
#macro BCK_CONTEST 13
#macro BCK_AIRPLANE 14
#macro BCK_HINT 15
#macro BCK_VOLCANO 16
#macro BCK_STORE 17
#macro BCK_HOUSE 18
#macro BCK_VICTORY 19
#macro BCK_WAHAII 20
#macro BCK_NOPE 21
#macro BCK_HOUSE2 22
#macro BCK_PHOTO 23
#macro BCK_CASTLE 24
#macro BCK_RECORDS2 25
#macro BCK_NONE 26

#macro enm_Student 0
#macro enm_TheTramp 1
#macro enm_Watchman 2
#macro enm_Barf 3
#macro enm_Everyman 4
#macro enm_Senior 5
#macro enm_Slasher 6
#macro enm_Vomitor 7
#macro enm_Fangirl 8
#macro enm_Reporter 9
#macro enm_Creep 10
#macro enm_CityFox 11
#macro enm_Mobster 12
#macro enm_Paparazi 13
#macro enm_Newsgirl 14
#macro enm_Winky 15
#macro enm_Honeybee 16
#macro enm_Radisher 17
#macro enm_Marooze 18
#macro enm_Seafoam 19
#macro enm_Teamon 20
#macro enm_Surenda 21
#macro enm_Swoosha 22
#macro enm_Crabby 23
#macro enm_RedFlag 24
#macro enm_Zyrup 25
#macro enm_GoodBoy 26
#macro enm_Otto 27
#macro enm_Boxers 28
#macro enm_Gumdrop 29
#macro enm_WildGuy 30
#macro enm_Squiddy1 31
#macro enm_Wabbit 32
#macro enm_Bloadent 33
#macro enm_Mailboxer 34
#macro enm_Squiddy2 35
#macro enm_Cerumean 36
#macro enm_Queenie 37
#macro enm_Coola 38
#macro enm_Squiddy3 39
#macro enm_Indigoo 40
#macro enm_Metallico 41
#macro enm_Carroman 42
#macro enm_Squiddy4 43
#macro enm_StirFox 44
#macro enm_Puddling 45
#macro enm_KayIX 46
#macro enm_Squiddy5 47
#macro enm_Arachnid 48
#macro enm_ToilOil 49
#macro enm_Leapfrog 50
#macro enm_Squiddy6 51
#macro enm_Shroud 52
#macro enm_Goldmold 53
#macro enm_Rhiannon 54
#macro enm_Squiddy7 55
#macro enm_Mooster 56
#macro enm_Snowhare 57
#macro enm_Hooaryoo 58
#macro enm_Squiddy9 59
#macro enm_Hilltula 60
#macro enm_FoxyFox 61
#macro enm_Slushie 62
#macro enm_Squiddy10 63
#macro enm_Batbrella 64
#macro enm_RojoAsp 65
#macro enm_Snaptrap 66
#macro enm_Rattler 67
#macro enm_Toady 68
#macro enm_Snailoid 69
#macro enm_Snailzor 70
#macro enm_Sewerat 71
#macro enm_Hooumai 72
#macro enm_AquaAsp 73
#macro enm_Crocodon 74
#macro enm_Covertail 75
#macro enm_Model 76
#macro enm_Jerkface 77
#macro enm_Coder 78
#macro enm_CodeBug 79
#macro enm_Hisstar 80
#macro enm_Starlet 81
#macro enm_Eldrick 82
#macro enm_Moriss 83
#macro enm_LilBrat 84
#macro enm_Parawing 85
#macro enm_Dummie 86
#macro enm_Wobbler 87
#macro enm_Skyjelly 88
#macro enm_ShyHare 89
#macro enm_Frenchie 90
#macro enm_German 91
#macro enm_Squiddy8 92
#macro enm_Scottish 93
#macro enm_Jaysin 94
#macro enm_TheBoss 95

#macro enm_SquiddyBar1 96
#macro enm_SquiddyBar2 97
#macro enm_SquiddyBar3 98
#macro enm_SquiddyBar4 99
#macro enm_SquiddyBar5 100
#macro enm_SquiddyBar6 101
#macro enm_SquiddyBar7 102

#macro food_Bread 0
#macro food_Burger 1
#macro food_Pasta 2
#macro food_Omelets 3
#macro food_PBJ 4
#macro food_Spaghetti 5
#macro food_Salmon 6
#macro food_Pizza 7
#macro food_Sushi 8
#macro food_Lobster 9
#macro food_Curry 10
#macro food_Roast 11
#macro food_Steak 12
#macro food_Kalamari 13
#macro food_Caviar 14
#macro food_Tomatoes 15